-- Generated by scripts/generate-inventory-seed-sql.mjs from diphu_inventory_1_data.json
-- Inventory: b1afabb6-9148-4111-8fd9-745240f41553
-- Stock: ON CONFLICT replaces quantity with JSON amount (default)
-- Note: batch IDs ending with day 00 were normalized to day 01 for production_day.
-- Reset mode: existing stock rows in this inventory not present in input are set to quantity 0.
BEGIN;

-- Batches: production_day from batchId; production_date = CURRENT_TIMESTAMP. If (inventory_id, batchId) already exists, INSERT is skipped (no duplicate batch).
INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/A01',
  'b1afabb6-9148-4111-8fd9-745240f41553',
  CURRENT_TIMESTAMP,
  DATE '2026-01-01',
  'Seeded from diphu_inventory_1_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

-- Stocks: sku by exact name; batch resolved by inventory + batchId
INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  19
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Smoked Pork 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  11
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Smoked Pork 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  9
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Less Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  32
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Less Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  16
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork More Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork More Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Lean Meat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  0
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Chops Rte 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Curry Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Curry Cut 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Ham Smoked (Uncut)'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  0
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Boston Butt 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Boston Butt 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  0
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Baby Back Rib 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Normal Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Trotters 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Trotters (Sliced) 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Belly With Skin 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Spare Rib 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  9
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Spare Rib 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Belly Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  7
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Back Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Prime Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Blood'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Young Pork 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  7
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Mortadella 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  13
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Sliced Belly 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Tenderloin 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Samosa 6 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Spring Roll 4 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Liver 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  9
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Innards 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Intestine 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  32
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Stew Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Head'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Ear'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  19
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Pickle 180 Gm (With Bambooshoot)'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Sausages Spicy 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  'b1afabb6-9148-4111-8fd9-745240f41553',
  s.id,
  b.id,
  0
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553' AND b."batchId" = '26/SFPL/A01'
WHERE s.name = 'Pork Bambooshoot Sausages 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

-- Set existing rows not present in the input list to zero
UPDATE "stocks" st
SET quantity = 0, last_updated = NOW()
WHERE st.inventory_id = 'b1afabb6-9148-4111-8fd9-745240f41553'
  AND NOT EXISTS (
    SELECT 1
    FROM "skus" s
    JOIN "batches" b ON b.id = st.batch_id AND b.inventory_id = st.inventory_id
    WHERE s.id = st.sku_id
      AND (
        (s.name = 'Smoked Pork 450 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Smoked Pork 250 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Less Fat 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Less Fat 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork More Fat 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork More Fat 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Lean Meat 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Chops Rte 200 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Curry Cut 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Curry Cut 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Ham Smoked (Uncut)' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Boston Butt 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Boston Butt 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Baby Back Rib 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Normal Chops 450 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Rib Chops 450 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Trotters 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Trotters (Sliced) 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Belly With Skin 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Spare Rib 450 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Spare Rib 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Belly Bacon 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Back Bacon 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Prime Bacon 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Blood' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Young Pork 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Ham Rte 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Mortadella 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Sliced Belly 450 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Tenderloin 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Samosa 6 Pcs' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Spring Roll 4 Pcs' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Liver 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Innards 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Intestine 1 Kg' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Stew Cut 500 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Head' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Ear' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Pickle 180 Gm (With Bambooshoot)' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Sausages Spicy 150 Gm' AND b."batchId" = '26/SFPL/A01') OR
        (s.name = 'Pork Bambooshoot Sausages 150 Gm' AND b."batchId" = '26/SFPL/A01')
      )
  );

COMMIT;