-- Generated by scripts/generate-inventory-seed-sql.mjs from diphu_inventory_data.json
-- Inventory: 0e625406-ddeb-45c8-815a-0183ffa9d163
BEGIN;

-- Batches: production_day parsed from batchId (YY/SFPL/{Month}{DD}); production_date = CURRENT_TIMESTAMP
INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D19',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-19',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D02',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-02',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C27',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-27',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C30',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-30',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D03',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-03',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D18',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-18',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C21',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-21',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D01',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-01',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D11',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-11',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D10',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-10',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D13',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-13',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D06',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-06',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D17',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-17',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C23',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-23',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C02',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-02',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C10',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-10',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C31',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-31',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C17',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-03-17',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D07',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-07',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D14',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2026-04-14',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '25/SFPL/K18',
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  CURRENT_TIMESTAMP,
  DATE '2025-11-18',
  'Seeded from diphu_inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

-- Stocks: sku by exact name; batch by inventory + batchId (works if batch pre-existed)
INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  9
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Smoked Pork 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  28
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D02'
WHERE s.name = 'Smoked Pork 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  25
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Pork Less Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C27'
WHERE s.name = 'Pork Less Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  7
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C30'
WHERE s.name = 'Pork Less Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D03'
WHERE s.name = 'Pork Less Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C27'
WHERE s.name = 'Pork Less Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  20
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork More Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  8
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C21'
WHERE s.name = 'Pork More Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Lean Meat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D01'
WHERE s.name = 'Pork Chops Rte 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  11
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Curry Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D11'
WHERE s.name = 'Pork Curry Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  7
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D10'
WHERE s.name = 'Pork Curry Cut 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Curry Cut 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D13'
WHERE s.name = 'Pork Curry Cut 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D06'
WHERE s.name = 'Pork Ham Smoked (Uncut)'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Boston Butt 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Boston Butt 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D17'
WHERE s.name = 'Pork Baby Back Rib 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C23'
WHERE s.name = 'Pork Normal Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C02'
WHERE s.name = 'Pork Normal Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D13'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C10'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C31'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D18'
WHERE s.name = 'Pork Trotters 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Pork Belly With Skin 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C23'
WHERE s.name = 'Pork Spare Rib 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C17'
WHERE s.name = 'Pork Belly Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/C17'
WHERE s.name = 'Pork Back Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D07'
WHERE s.name = 'Pork Prime Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Pork Blood'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D14'
WHERE s.name = 'Young Pork 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  8
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '0e625406-ddeb-45c8-815a-0183ffa9d163',
  s.id,
  b.id,
  8
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '0e625406-ddeb-45c8-815a-0183ffa9d163' AND b."batchId" = '25/SFPL/K18'
WHERE s.name = 'Pork Mortadella 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

COMMIT;