-- Generated by scripts/generate-inventory-seed-sql.mjs from inventory_data.json
-- Inventory: 6ced05cf-db66-4b69-8aff-61217300b235
-- Stock: ON CONFLICT replaces quantity with JSON amount (default)
BEGIN;

-- Batches: production_day from batchId; production_date = CURRENT_TIMESTAMP. If (inventory_id, batchId) already exists, INSERT is skipped (no duplicate batch).
INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D09',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-09',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D04',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-04',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D08',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-08',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C25',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-25',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C19',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-19',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C27',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-27',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D10',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-10',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D06',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-06',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C21',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-21',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D03',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-03',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C23',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-23',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C02',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-02',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B07',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-07',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B25',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-25',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C31',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-31',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D07',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-07',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D11',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-11',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D26',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-26',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D02',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-02',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C28',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-28',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/A10',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-01-10',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '25/SFPL/J29',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2025-10-29',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/A17',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-01-17',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B19',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-19',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B10',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-10',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B11',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-11',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D01',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-04-01',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C26',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-26',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C17',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-17',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/C13',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-03-13',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/B14',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-02-14',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/A30',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-01-30',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/A12',
  '6ced05cf-db66-4b69-8aff-61217300b235',
  CURRENT_TIMESTAMP,
  DATE '2026-01-12',
  'Seeded from inventory_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

-- Stocks: sku by exact name; batch resolved by inventory + batchId
INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D09'
WHERE s.name = 'Pork Baby Back Rib 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D04'
WHERE s.name = 'Pork Boston Butt 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  21
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D08'
WHERE s.name = 'Pork Curry Cut 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C25'
WHERE s.name = 'Pork Curry Cut 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C19'
WHERE s.name = 'Pork Curry Cut 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C27'
WHERE s.name = 'Pork Curry Cut 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  37
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D10'
WHERE s.name = 'Pork Curry Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D06'
WHERE s.name = 'Pork Curry Cut 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D06'
WHERE s.name = 'Pork Ham Boneless 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D10'
WHERE s.name = 'Pork Lean Meat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  17
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C21'
WHERE s.name = 'Pork Less Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D03'
WHERE s.name = 'Pork Less Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  25
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D03'
WHERE s.name = 'Pork Less Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  18
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D10'
WHERE s.name = 'Pork More Fat 1 Kg'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  34
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D08'
WHERE s.name = 'Pork More Fat 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  6
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C23'
WHERE s.name = 'Pork Normal Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C02'
WHERE s.name = 'Pork Normal Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B07'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B25'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C31'
WHERE s.name = 'Pork Rib Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D07'
WHERE s.name = 'Pork Sliced Belly 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D11'
WHERE s.name = 'Pork Sliced Belly 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D07'
WHERE s.name = 'Pork Sliced Belly 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C23'
WHERE s.name = 'Pork Spare Ribs Chops 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D26'
WHERE s.name = 'Pork Tenderloin 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  38
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D02'
WHERE s.name = 'Smoked Pork 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  49
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D02'
WHERE s.name = 'Smoked Pork 450 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  4
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C28'
WHERE s.name = 'Young Pork 500 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  18
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/A10'
WHERE s.name = 'Pork Mortadella 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  2
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '25/SFPL/J29'
WHERE s.name = 'Pork Mortadella 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/A17'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  12
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B19'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B10'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B11'
WHERE s.name = 'Pork Ham Rte 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  11
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D01'
WHERE s.name = 'Pork Chops Rte 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  8
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D01'
WHERE s.name = 'Pork Rib Chops Rte 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C26'
WHERE s.name = 'Pork Momo 10 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  14
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B19'
WHERE s.name = 'Pork Salami Spicy 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C27'
WHERE s.name = 'Pork Salami Spicy 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  5
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/A10'
WHERE s.name = 'Pork Salami Spicy 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  20
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C17'
WHERE s.name = 'Pork Belly Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C13'
WHERE s.name = 'Pork Belly Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  15
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D04'
WHERE s.name = 'Pork Prime Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  18
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C17'
WHERE s.name = 'Pork Back Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D04'
WHERE s.name = 'Pork Back Bacon 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/B14'
WHERE s.name = 'Pork Seekh Kebab 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  9
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C28'
WHERE s.name = 'Pork Seekh Kebab 200 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/A30'
WHERE s.name = 'Pork Bambooshoot Sausages 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  1
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/A12'
WHERE s.name = 'Pork Bambooshoot Sausages 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  8
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/D06'
WHERE s.name = 'Pork Bambooshoot Sausages 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  18
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C13'
WHERE s.name = 'Pork Sausages Spicy 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  17
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C13'
WHERE s.name = 'Pork Sausages Plain 150 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C26'
WHERE s.name = 'Pork Spring Roll 4 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C23'
WHERE s.name = 'Pork Samosa 6 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '6ced05cf-db66-4b69-8aff-61217300b235',
  s.id,
  b.id,
  3
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '6ced05cf-db66-4b69-8aff-61217300b235' AND b."batchId" = '26/SFPL/C26'
WHERE s.name = 'Pork Samosa 6 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = EXCLUDED.quantity, last_updated = NOW();

COMMIT;