-- Generated by scripts/generate-inventory-seed-sql.mjs from production_data.json
-- Inventory: 12e09980-e3d1-4aa9-ab7c-81c7a944caa0
-- Stock: ON CONFLICT adds JSON amount to existing quantity (--add-to-existing-stock)
BEGIN;

-- Batches: production_day from batchId; production_date = CURRENT_TIMESTAMP. If (inventory_id, batchId) already exists, INSERT is skipped (no duplicate batch).
INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D19',
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  CURRENT_TIMESTAMP,
  DATE '2026-04-19',
  'Seeded from production_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

INSERT INTO "batches" (id, "batchId", inventory_id, production_date, production_day, remark)
VALUES (
  gen_random_uuid()::text,
  '26/SFPL/D22',
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  CURRENT_TIMESTAMP,
  DATE '2026-04-22',
  'Seeded from production_data.json'
)
ON CONFLICT ("inventory_id", "batchId") DO NOTHING;

-- Stocks: sku by exact name; batch resolved by inventory + batchId
INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Pork Momo 10 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  17
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D22'
WHERE s.name = 'Shredded Pickle 150 gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  20
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D22'
WHERE s.name = 'Pork Pickle 180 Gm (with Bambooshoot)'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  20
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D22'
WHERE s.name = 'Pork Pickle 180 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D22'
WHERE s.name = 'Chicken Lollipop 6 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  10
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D19'
WHERE s.name = 'Chicken Momo 10 Pcs'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

INSERT INTO "stocks" AS st (id, inventory_id, sku_id, batch_id, quantity)
SELECT
  gen_random_uuid()::text,
  '12e09980-e3d1-4aa9-ab7c-81c7a944caa0',
  s.id,
  b.id,
  19
FROM "skus" s
INNER JOIN "batches" b
  ON b.inventory_id = '12e09980-e3d1-4aa9-ab7c-81c7a944caa0' AND b."batchId" = '26/SFPL/D22'
WHERE s.name = 'Pork Curry Cut 250 Gm'
LIMIT 1
ON CONFLICT (inventory_id, sku_id, batch_id)
DO UPDATE SET quantity = st.quantity + EXCLUDED.quantity, last_updated = NOW();

COMMIT;